"""initial schema

Revision ID: b783911fbd84
Revises: 
Create Date: 2026-09-07 01:52:33.648364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b783911fbd84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='adminrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'READ', 'RESOLVED', name='contactstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_table('customers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_stripe_customer_id'), 'customers', ['stripe_customer_id'], unique=True)
    op.create_table('discount_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('stripe_coupon_id', sa.String(length=255), nullable=True),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('amount_off_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_codes'))
    )
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=True)
    op.create_table('packages',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_interval', sa.Enum('MONTHLY', 'THREE_MONTH', 'SIX_MONTH', 'TWELVE_MONTH', name='billinginterval', native_enum=False, length=20), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    op.create_table('programmes',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('everfit_programme_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programmes'))
    )
    op.create_index(op.f('ix_programmes_slug'), 'programmes', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_stripe_event_id'), 'webhook_events', ['stripe_event_id'], unique=True)
    op.create_table('assignment_rules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_assignment_rules_programme_id_programmes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_rules'))
    )
    op.create_index(op.f('ix_assignment_rules_priority'), 'assignment_rules', ['priority'], unique=False)
    op.create_table('memberships',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_latest_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'ONBOARDING_PENDING', 'ONBOARDING_COMPLETE', 'PROVISIONING', 'PROVISIONED', 'PROVISIONING_FAILED', 'PAYMENT_FAILED', 'CANCELED', 'REFUNDED', name='membershipstatus', native_enum=False, length=30), nullable=False),
    sa.Column('discount_code_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_memberships_customer_id_customers')),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], name=op.f('fk_memberships_discount_code_id_discount_codes')),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_memberships_package_id_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('stripe_checkout_session_id', name=op.f('uq_memberships_stripe_checkout_session_id'))
    )
    op.create_index(op.f('ix_memberships_customer_id'), 'memberships', ['customer_id'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_index(op.f('ix_memberships_stripe_latest_payment_intent_id'), 'memberships', ['stripe_latest_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_memberships_stripe_subscription_id'), 'memberships', ['stripe_subscription_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_password_reset_tokens_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_customer_id'), 'password_reset_tokens', ['customer_id'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_membership_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_admin_audit_logs_admin_user_id_admin_users')),
    sa.ForeignKeyConstraint(['target_membership_id'], ['memberships.id'], name=op.f('fk_admin_audit_logs_target_membership_id_memberships')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_table('everfit_accounts',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('everfit_client_id', sa.String(length=255), nullable=True),
    sa.Column('programme_id', sa.Uuid(), nullable=True),
    sa.Column('matched_rule_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'CLIENT_CREATED', 'PROGRAMME_ASSIGNED', 'ACTIVATED', 'FAILED', name='everfitstatus', native_enum=False, length=20), nullable=False),
    sa.Column('access_url', sa.String(length=500), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['assignment_rules.id'], name=op.f('fk_everfit_accounts_matched_rule_id_assignment_rules')),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_everfit_accounts_membership_id_memberships')),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_everfit_accounts_programme_id_programmes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_everfit_accounts')),
    sa.UniqueConstraint('membership_id', name=op.f('uq_everfit_accounts_membership_id'))
    )
    op.create_table('onboarding_responses',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goal', sa.Enum('FAT_LOSS', 'MUSCLE_BUILDING', 'RECOMPOSITION', 'PERFORMANCE', 'GENERAL_HEALTH', name='goal', native_enum=False, length=30), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('body_composition_goal', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_range', sa.String(length=50), nullable=True),
    sa.Column('training_experience', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experiencelevel', native_enum=False, length=20), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=True),
    sa.Column('preferred_training_days', sa.JSON(), nullable=True),
    sa.Column('training_location', sa.Enum('GYM', 'HOME', 'HYBRID', name='traininglocation', native_enum=False, length=20), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('daily_steps', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.String(length=50), nullable=True),
    sa.Column('current_calorie_intake', sa.Integer(), nullable=True),
    sa.Column('food_preferences', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('intolerances', sa.Text(), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('cooking_ability', sa.String(length=50), nullable=True),
    sa.Column('food_budget', sa.String(length=50), nullable=True),
    sa.Column('injuries', sa.Text(), nullable=True),
    sa.Column('physical_limitations', sa.Text(), nullable=True),
    sa.Column('health_screening_answers', sa.JSON(), nullable=True),
    sa.Column('progress_photos_provided', sa.Boolean(), nullable=False),
    sa.Column('answers_raw', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_onboarding_responses_membership_id_memberships')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_responses')),
    sa.UniqueConstraint('membership_id', name=op.f('uq_onboarding_responses_membership_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_responses')
    op.drop_table('everfit_accounts')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_password_reset_tokens_customer_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_memberships_stripe_subscription_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_stripe_latest_payment_intent_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_customer_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_assignment_rules_priority'), table_name='assignment_rules')
    op.drop_table('assignment_rules')
    op.drop_index(op.f('ix_webhook_events_stripe_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_programmes_slug'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_customers_stripe_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
