"""add onboarding sleep_quality

Revision ID: e3dcd0d9a76b
Revises: b783911fbd84
Create Date: 2026-09-08 16:58:59.060034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dcd0d9a76b'
down_revision: Union[str, None] = 'b783911fbd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_responses', sa.Column('sleep_quality', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_responses', 'sleep_quality')
    # ### end Alembic commands ###
